### ISSUE TITLE
Method signature spelling incorrect on deleteDocumentWithId: in CDTDatabase.h and .m

### ISSUE THREAD

**Issue by gmgershon** [cloudant/objective-cloudant#48]
- (void)deleteDocumentWithId:(NSString *)documentId
                  revisionId:(NSString *)revId
         completetionHandler:(void (^)(NSInteger statusCode, NSError *_Nullable))completionHandler

Should be completionHandler: and not completetionHandler (remove "te")

**Comment by rhyshort** [comment]
Hi thanks for reporting this and sorry for the slow reply, we refocused our efforts on a library written in swift ([SwiftCloudant](https://github.com/cloudant/swift-cloudant)). 

We have deprecated this library and recommend that you use [SwiftCloudant](https://github.com/cloudant/swift-cloudant) instead.  It is more fully featured that
objective-cloudant, and should meet your needs. If you have any problems using [SwiftCloudant](https://github.com/cloudant/swift-cloudant) please raise an issue over on the [SwiftCloudant](https://github.com/cloudant/swift-cloudant/issues/new) repo.
