### ISSUE TITLE
Errors in README.md code for Swift read and delete examples

### ISSUE THREAD

**Issue by gmgershon** [cloudant/objective-cloudant#49]
//read document
db.getDocumentWithId("doc1",
    completionHander:(document, operationError) -> Void {
        if let error = operationError {
            println("Encountered an error reading a document. Error: \(error)")
        } else {
            println("Read document \(document!)")
        }
})

completionHandler in error: misplaced opening brace and missing "in" after Void

println needs to be replaced with print in two places

----------------

//delete document
db.deleteDocumentWithId("doc1",
    revisionId: "1-revisionidhere",
    completionHandler: { (statusCode, operationError) -> Void in
        if let error = operationError {
            print("Encountered error: \(error!)")
        } else {
            print("document deleted")
        }
})

remove exclamation mark in: print("Encountered error: \(error!)")

**Comment by rhyshort** [comment]
Thanks for reporting this, it is now fixed on master.
